language: julia

arch:
  - amd64
  - arm64-graviton2

virt: lxd

group: edge

os:
  - linux

julia:
  - 0.7
  - 1.0
  - 1.2
  - 1.3
  - nightly

notifications:
  email: false

matrix:
  allow_failures:
    - julia: nightly
    - arch: arm64-graviton2

jobs:
  fast_finish: true

# script:
#   - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#   - julia --check-bounds=yes -e 'using Pkg; Pkg.clone(pwd()); Pkg.test("TransformUtils"; coverage=true)'

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("TransformUtils")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
