language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.2
  - 1.3
  - nightly

notifications:
  email: false

matrix:
  allow_failures:
    - julia: nightly

jobs:
  fast_finish: true

# script:
#   - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#   - julia --check-bounds=yes -e 'using Pkg; Pkg.clone(pwd()); Pkg.test("TransformUtils"; coverage=true)'

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("TransformUtils")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
